services:
  web:
    build: .
    working_dir: /var/www
    container_name: product_listing-web
    volumes:
      - ../:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    container_name: product_listing-nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: mysql:5.6
    ports:
      - "3338:3306"
    container_name: product_listing-db
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
